version: "v0"
kind: RateLimit
name: "/foo/bar"
description: "/foo/bar"
spec:
  limit:
    count: 10
    duration: 1m
    enabled: true
  conditions:
    path: "/foo/bar"
---
version: "v0"
kind: RateLimit
name: "/foo/baz"
description: "/foo/baz"
spec:
  limit:
    count: 5
    duration: 1m
    enabled: false
  conditions:
    path: "/foo/baz"
