version: "v0"
kind: Jail
name: "/foo/bar"
description: "/foo/bar"
jailSpec:
  limit:
    count: 10
    duration: 10s
    enabled: true
  conditions:
    path: "/foo/bar"
  banDuration: 30s # Keep this duration short as it's used in tests
---
version: "v0"
kind: Jail
name: "/foo/baz"
description: "/foo/baz"
jailSpec:
  limit:
    count: 5
    duration: 1m
    enabled: false
  conditions:
    path: "/foo/baz"
  banDuration: 30s # Keep this duration short as it's used in tests
