version: "v0"
kind: Jail
name: "/foo/bar"
description: "/foo/bar"
spec:
  limit:
    count: 10
    duration: 10s
    enabled: true
  conditions:
    path: "/foo/bar"
  ban_duration: 30s # Keep this duration short as it's used in tests
---
version: "v0"
kind: Jail
name: "/foo/baz"
description: "/foo/baz"
spec:
  limit:
    count: 5
    duration: 1m
    enabled: false
  conditions:
    path: "/foo/baz"
  ban_duration: 30s # Keep this duration short as it's used in tests
