version: "3"
services:

  redis:
    image: redis:alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - data
    volumes:
      - redis-data:/data

  ratelimit:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 6070:6070
    depends_on:
      - redis
    networks:
      - data
    links:
      - redis
    volumes:
      - ./examples:/data/
    environment:
      - USE_STATSD=false
      - LOG_LEVEL=debug
      - REDIS_SOCKET_TYPE=tcp
      - REDIS_URL=redis:6379
      - RUNTIME_ROOT=/data
      - RUNTIME_SUBDIRECTORY=ratelimit

networks:
  data:

volumes:
  redis-data:
  ratelimit-data:
