// Code generated by "stringer -type=RequestBlockerResp"; DO NOT EDIT.

package guardian

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AllowedStop-0]
	_ = x[AllowedContinue-1]
	_ = x[BlockedStop-2]
}

const _RequestBlockerResp_name = "AllowedStopAllowedContinueBlockedStop"

var _RequestBlockerResp_index = [...]uint8{0, 11, 26, 37}

func (i RequestBlockerResp) String() string {
	if i < 0 || i >= RequestBlockerResp(len(_RequestBlockerResp_index)-1) {
		return "RequestBlockerResp(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RequestBlockerResp_name[_RequestBlockerResp_index[i]:_RequestBlockerResp_index[i+1]]
}
